--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.131.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021.01.18. 16:45:46
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE tdb;

--
-- Drop table "users"
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE tdb;

--
-- Create table "users"
--
CREATE TABLE users (
  id INT(11) NOT NULL,
  nev VARCHAR(80) NOT NULL,
  nem VARCHAR(80) NOT NULL,
  adat INT(11) NOT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1365
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Yogesh Singh', 'ffi', 12),
(2, 'Sonarika Bhadoria', 'no', 45),
(3, 'Vishal Sahu', 'ffi', 345),
(4, 'Vijay mourya', 'ffi', 135),
(5, 'Hocky György', 'ffi', 15),
(6, 'Kika Kata', 'no', 13),
(7, 'Uj Ember', 'no', 1231),
(8, 'Grey Groy', 'ffi', 123),
(9, 'admin', 'admin', 11),
(10, 'Szoke Cigány', 'no', 123),
(11, 'Anna', 'no', 100),
(12, 'Shitz', 'Gigz', 123);
-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
